# permissions for end users to view postgresroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresrole-viewer-role
rules:
- apiGroups:
  - database.croz.net
  resources:
  - postgresroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.croz.net
  resources:
  - postgresroles/status
  verbs:
  - get
