# permissions for end users to edit postgresroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresrole-editor-role
rules:
- apiGroups:
  - database.croz.net
  resources:
  - postgresroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.croz.net
  resources:
  - postgresroles/status
  verbs:
  - get
